remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Identifying Software Inefficiency with Fine-grained Value Profilers
description: HELD IN CONJUNCTION WITH THE IEEE INTERATIONAL CONFERENCE ON CLUSTER COMPUTING (Cluster 2024)
